routes/web.php
    Route::get('find_branch_staff_attendance_report','HRM\StaffController@find_branch_staff_attendance_report');
    
    


    Route::get('find_company_wise_eobiepf','HRM\StaffController@find_company_wise_eobiepf');
    Route::get('find_company_branch_wise_eobiepf','HRM\StaffController@find_company_branch_wise_eobiepf');








    Route::get('find_board','Payroll\AttendanceController@get_board');
    Route::get('find_board_program','Payroll\AttendanceController@get_program');
    Route::get('find_board_program_class','Payroll\AttendanceController@get_program_class');
    Route::get('find_board_program_class_section','Payroll\AttendanceController@get_program_class_section');
    Route::get('find_board_program_class_section_courses','Payroll\AttendanceController@get_program_class_section_course');

    Route::get('teacher_attendance_daywise','Payroll\AttendanceController@store_teacher_attendance_daywise');

    Route::get('find_board_program_class_section_students','Payroll\AttendanceController@get_program_class_section_students');


    Route::get('find_course_name','Payroll\AttendanceController@get_course_name');

    Route::get('find_board_program_class_section_courses_students','Payroll\AttendanceController@get_program_class_section_students');


Route::get('find_program_courses_timetable','Payroll\AttendanceController@get_program_courses_timetable');

    


    Route::resource('leave_management', 'Payroll\LeaveManagementController');

    Route::get('/leaverequestlist', ['uses' => 'Payroll\LeaveManagementController@leaveRequestList', 'as' => 'leave_request.list']);

    Route::get('/leaverequest/approve/{id}', ['uses' => 'Payroll\LeaveManagementController@leaveRequestApprove', 'as' => 'leave_request.approve']);

    Route::get('/leaverequest/unapprove/{id}', ['uses' => 'Payroll\LeaveManagementController@leaveRequestUnapprove', 'as' => 'leave_request.unapprove']);
    Route::get('/staff.create', ['uses' => 'HRM\StaffController@create', 'as' => 'staff.create']);
    // Employees Resrouce Ends Here
    //Banks Resrouce Starts Here
    Route::resource('banks', 'Admin\BanksController');
    Route::post('banks_mass_destroy', ['uses' => 'Admin\BanksController@massDestroy', 'as' => 'banks.mass_destroy']);
    // Banks Resrouce Ends Here
    //Banksdetail Resrouce Starts Here
    Route::resource('bank_detail', 'Admin\BankDetailController');
    Route::post('bank_detail_mass_destroy', ['uses' => 'Admin\BankDetailController@massDestroy', 'as' => 'bank_detail.mass_destroy']);
    // Banksdetail Resrouce Ends Here

    // Suppliers Resrouce Starts Here
    Route::post('suppliers/delete', ['uses' => 'Admin\SuppliersController@delete', 'as' => 'suppliers.delete']);
    Route::get('supliers/datatables', ['uses' => 'Admin\SuppliersController@datatables', 'as' => 'supliers.datatables']);
    Route::resource('suppliers', 'Admin\SuppliersController');
    Route::patch('suppliers/active/{id}', ['uses' => 'Admin\SuppliersController@active', 'as' => 'suppliers.active']);
    Route::patch('suppliers/inactive/{id}', ['uses' => 'Admin\SuppliersController@inactive', 'as' => 'suppliers.inactive']);
    Route::post('suppliers_mass_destroy', ['uses' => 'Admin\SuppliersController@massDestroy', 'as' => 'suppliers.mass_destroy']);
    // Suppliers Resrouce Ends Here

    // Sales Invoices Starts Here
    Route::get('/salesinvoice', ['uses' => 'Admin\SalesInvoiceController@index', 'as' => 'salesinvoice.index']);
    Route::get('/salesinvoice/create', ['uses' => 'Admin\SalesInvoiceController@create', 'as' => 'salesinvoice.create']);
    Route::get('/salesinvoice/view/{id}', ['uses' => 'Admin\SalesInvoiceController@view', 'as' => 'salesinvoice.view']);
    Route::get('/salesinvoice/view/downloadPDF/{id}', ['uses' => 'Admin\SalesInvoiceController@downloadPDF', 'as' => 'salesinvoice.pdf']);
    Route::post('/salesinvoice/store', ['uses' => 'Admin\SalesInvoiceController@store', 'as' => 'salesinvoice.store']);
    Route::post('salesinvoice/update/{id}', ['uses' => 'Admin\SalesInvoiceController@update', 'as' => 'salesinvoice.update']);
    Route::post('/salesinvoice/getOrderDetail', ['uses' => 'Admin\SalesInvoiceController@getOrderDetail', 'as' => 'salesinvoice.getOrderDetail']);
    Route::get('salesinvoice/datatables', ['uses' => 'Admin\SalesInvoiceController@datatables', 'as' => 'salesinvoice.datatables']);
    Route::post('salesinvoice/confirm', ['uses' => 'Admin\SalesInvoiceController@confirm', 'as' => 'salesinvoice.confirm']);
    Route::post('salesinvoice/update_invoice/{id}', ['uses' => 'Admin\SalesInvoiceController@update_invoice', 'as' => 'salesinvoice.update_invoice']);

    Route::get('/salesinvoice/{id}/edit', ['uses' => 'Admin\SalesInvoiceController@edit', 'as' => 'salesinvoice.edit']);
    //    Route::resource('salesinvoice', 'Admin\SalesInvoiceController');
    //Orders Resrouce Starts Here
    Route::post('orders/delete', ['uses' => 'Admin\OrdersController@delete', 'as' => 'orders.delete']);
    Route::get('importindex', ['uses' => 'Admin\OrdersController@importindex', 'as' => 'orders.importindex']);
    Route::get('orders/datatables', ['uses' => 'Admin\OrdersController@datatables', 'as' => 'orders.datatables']);
    Route::get('orders/importdatatables', ['uses' => 'Admin\OrdersController@importdatatables', 'as' => 'orders.importdatatables']);
    Route::get('orders/productlist', 'Admin\OrdersController@productlist')->name('orders.productlist');
    Route::resource('orders', 'Admin\OrdersController');
    Route::post('orders_mass_destroy', ['uses' => 'Admin\OrdersController@massDestroy', 'as' => 'orders.mass_destroy']);
    Route::post('stockitems/delete', ['uses' => 'Admin\StockItemsController@delete', 'as' => 'stockitems.delete']);
    Route::post('stockitems/datatables', ['uses' => 'Admin\StockItemsController@datatables', 'as' => 'stockitems.datatables']);
    Route::get('stockitems/models/{model_no}', 'Admin\StockItemsController@modelno')->name('stockitems.models');
    Route::get('stockitems/performa/{lc_no}/{sup_id}', 'Admin\StockItemsController@performa')->name('stockitems.performa');
    Route::get('stockitems/inventoryproduct', 'Admin\StockItemsController@inventoryproduct')->name('stockitems.inventoryproduct');
    //Orders Routeesrouce End Here
    Route::get('cinvoice/datatables', ['uses' => 'Admin\ComercialInvoiceController@datatables', 'as' => 'cinvoice.datatables']);
    Route::resource('cinvoice', 'Admin\ComercialInvoiceController');
    Route::get('cinvoice/productlist/{listvalue}', 'Admin\ComercialInvoiceController@getprpforma')->name('cinvoice.productlist');
    Route::get('cinvoice/costing/{ComercialInvoiceModel}', 'Admin\ComercialInvoiceController@lccosting')->name('cinvoice.costing');
    Route::post('cinvoice/cost', 'Admin\ComercialInvoiceController@costcalculation')->name('cinvoice.cost');
    Route::post('grimport/upd/{id}', ['uses' => 'Admin\ComercialInvoiceController@update', 'as' => 'comercialinvoiceupd.update']);
    Route::get('cinvoice/viewduty/{ComercialInvoiceModel}', 'Admin\ComercialInvoiceController@viewduty')->name('cinvoice.viewduty');
    Route::patch('cinvoice/viewduty/active/{id}', ['uses' => 'Admin\ComercialInvoiceController@active', 'as' => 'comercialinvoice.active']);
    Route::patch('cinvoice/viewduty/inactive/{id}', ['uses' => 'Admin\ComercialInvoiceController@inactive', 'as' => 'comercialinvoice.inactive']);

    //Sales Resrouce Starts Here
    Route::get('sales/produtsdetail/{id}', 'Admin\SalesController@produtsdetail')->name('sales.produtsdetail');
    Route::get('sales/produtscol/{id}', 'Admin\SalesController@produtscol')->name('sales.produtscol');
    Route::resource('sales', 'Admin\SalesController');
    Route::patch('sales/active/{id}', ['uses' => 'Admin\SalesController@active', 'as' => 'sales.active']);
    Route::patch('sales/inactive/{id}', ['uses' => 'Admin\SalesController@inactive', 'as' => 'sales.inactive']);
    Route::post('sales_mass_destroy', ['uses' => 'Admin\SalesController@massDestroy', 'as' => 'sales.mass_destroy']);
    //Sales Resrouce Ends Here
    // goods receipt Resrouce Starts Here
    // Route::post('products/delete', ['uses' => 'Admin\GoodsIssueController@delete', 'as' => 'products.delete']);
    Route::get('inventorytransfer/stocklist', 'Admin\InventoryTransferController@stocklist')->name('inventorytransfer.stocklist');
    Route::get('inventorytransfer/datatables', ['uses' => 'Admin\InventoryTransferController@datatables', 'as' => 'inventorytransfer.datatables']);
    Route::get('inventorytransfer/items/{id}', 'Admin\InventoryTransferController@stockrecord')->name('inventorytransfer.items');
    Route::resource('inventorytransfer', 'Admin\InventoryTransferController');
    // goods receipt Resrouce Ends Here

    // goods receipt Resrouce Starts Here
    // Route::post('products/delete', ['uses' => 'Admin\GoodsIssueController@delete', 'as' => 'products.delete']);
    Route::get('goodsreceipt/datatables', ['uses' => 'Admin\GoodsReceiptController@datatables', 'as' => 'goodsreceipt.datatables']);
    Route::get('goodsreceipt/product/{lc_no}/{sup_id}', 'Admin\GoodsReceiptController@getproduct')->name('goodsreceipt.product');
    Route::resource('goodsreceipt', 'Admin\GoodsReceiptController');
    // goods receipt Resrouce Ends Here

    // goods issue Resrouce Starts Here
    // Route::post('products/delete', ['uses' => 'Admin\GoodsIssueController@delete', 'as' => 'products.delete']);
    Route::get('goodsissue/datatables', ['uses' => 'Admin\GoodsIssueController@datatables', 'as' => 'goodsissue.datatables']);
    Route::get('goodsissue/items/{id}', 'Admin\GoodsIssueController@stockrecord')->name('goodsissue.items');
    Route::resource('goodsissue', 'Admin\GoodsIssueController');
    // goods issue Resrouce Ends Here

    //Stockitems Resrouce Starts Here

    Route::get('stockitems/performa/{lc_no}', 'Admin\StockItemsController@performa')->name('stockitems.performa');

resources/views/admin/salesinvoice/create.blade.php
@extends('layouts.app')

@section('breadcrumbs')
    <section class="content-header" style="padding: 10px 15px !important;">
        <h1>Sale Order</h1>
    </section>
@stop

<style>
    .select2{
        width: 100% !important;
    }
    .amount_section{
        margin-top: 30px;
    }

    .form-group{
        width: 100%;
        float: left;
    }

</style>

@section('content')
    <div class="box box-primary">

        <div class="box-header with-border">
            <h3 class="box-title">Sale Order</h3>
            <a href="{{ route('admin.salesinvoice.index') }}" class="btn btn-success pull-right">Back</a>
        </div>


        <!-- /.box-header -->
        <!-- form start -->
        {!! Form::open(['method' => 'POST', 'route' => ['admin.saleinvoice.store'], 'id' => 'validation-form']) !!}
        <div class="box-body">
            @include('admin.saleseinvoice.fields')

        <!-- /.box-body -->


                {{--
                --}}{{--product list of Purchase request--}}{{--
                @include('admin.purchaseorder.product_list_of_request')--}}
                <div id="prodcut"></div>

                @include('admin.saleseorder.caluculate_total_form')

                <div class="box-footer">

                    {!! Form::submit(trans('global.app_save'), ['class' => 'btn btn-danger globalSaveBtn']) !!}
                </div>
                @include('admin.saleseorder.items_template')

                {!! Form::close() !!}
        </div>
    </div>


@stop

@section('javascript')
    <script src="{{ url('public/js/admin/saleinvoice/sale_invoice_create_modify.js') }}" type="text/javascript"></script>
@endsection

resources/views/admin/salesinvoice/edit.blade.php
@extends('layouts.app')

@section('stylesheet')

    <style>
        .example-template > li {
            display: inline-block;
            float: left;
            margin: 0 8px 8px 0;
        }
        .list-style-none{
            list-style: none;
        }
    </style>
@stop

@section('breadcrumbs')
    <section class="content-header" style="padding: 10px 15px !important;">
        <h1>Purchase Order</h1>
    </section>
@stop

@section('content')
    <div class="box box-primary">
        <div class="box-header with-border">
            <h3 class="box-title">Add Performa Detail</h3>
            <a href="{{ route('admin.orders.index') }}" class="btn btn-success pull-right">Back</a>
        </div>
        <!-- /.box-header -->
        <!-- form start -->

        {!! Form::model($Orders, ['method' => 'PUT', 'id' => 'validation-form','route' => ['admin.orders.update', $Orders->id]]) !!}

        <div class="box-body">
                <div class="col-xs-12 form-group">
                    <div class="col-xs-4 form-group @if($errors->has('perfomra_no')) has-error @endif">
                        {!! Form::label('perfomra_no', 'Performa Number*', ['class' => 'control-label']) !!}
                        <input id="perfomra_no" class="form-control" type="text" name="perfomra_no" value="{{$Orders->perfomra_no}}" />
                    </div>
                    <div class="col-xs-4 form-group @if($errors->has('sal_no')) has-error @endif">
                        {!! Form::label('sale_no', 'Sales Order Number*', ['class' => 'control-label']) !!}
                        <input id="sale_no" class="form-control" type="text" name="sale_no" value="{{$Orders->sale_order_no}}" />
                    </div>
                    <div class="col-xs-4 form-group @if($errors->has('shipping')) has-error @endif">
                        {!! Form::label('shipping', 'Shipping Via*', ['class' => 'control-label']) !!}
                        <input id="shipping" class="form-control" type="text" name="shipping" value="{{$Orders->shipping}}" />
                    </div>
                </div>
                <div class="col-xs-12 form-group">
                    <div class="col-xs-4 form-group @if($errors->has('sal_date')) has-error @endif">
                        {!! Form::label('sal_date', 'Purchase Date', ['class' => 'control-label']) !!}
                        {!! Form::text('sal_date', old('sal_date'), ['id' => 'sal_date','class' => 'form-control datepicker', 'placeholder' => '' ]) !!}
                        @if($errors->has('sal_date'))
                            <span class="help-block">
                            {{ $errors->first('sal_date') }}
                            </span>
                        @endif
                    </div>
                    <div class="col-xs-4 form-group @if($errors->has('valid_upto')) has-error @endif">
                        {!! Form::label('valid_upto', 'On/About', ['class' => 'control-label']) !!}
                        {!! Form::text('valid_upto', old('valid_upto'), ['id' => 'valid_upto','class' => 'form-control datepicker', 'placeholder' => '']) !!}
                        @if($errors->has('valid_upto'))
                            <span class="help-block">
                                {{ $errors->first('valid_upto') }}
                                </span>
                        @endif
                    </div>
                    <div class="col-xs-4 form-group @if($errors->has('soruce')) has-error @endif">
                        {!! Form::label('soruce', 'From*', ['class' => 'control-label']) !!}
                        <input id="soruce" class="form-control" type="text" name="soruce" value="{{$Orders->soruce}}" />
                    </div>


                </div>

                <div class="col-xs-12 form-group">

                    <div class="col-xs-4 form-group @if($errors->has('destination')) has-error @endif">
                        {!! Form::label('destination', 'To*', ['class' => 'control-label']) !!}
                        <input id="destination" class="form-control" type="text" name="destination" value="{{$Orders->destination}}" />
                    </div>
                    <div class="col-xs-4  form-group @if($errors->has('status')) has-error @endif">
                        {!! Form::label('status', 'Order Status *', ['class' => 'control-label']) !!}
                        {!!  Form::select('status', [
                            '' => 'Select Order Status',
                            '1' => 'In Process',
                            '2' => 'Approved',
                            '3' => 'In Bound',
                            '4' => 'In Transit',
                            '5' => 'Completed',],
                            null,
                            ['class' => 'form-control select2'])
                        !!}

                        @if($errors->has('status'))
                            <span class="help-block">
                        {{ $errors->first('status') }}
                        </span>
                        @endif
                    </div>
                </div>
                <div class="col-xs-12 form-group">

                    <div class="col-xs-4 form-group @if($errors->has('po_number')) has-error @endif">
                        {!! Form::label('po_number', 'Po No*', ['class' => 'control-label']) !!}
                        {!! Form::text('po_number', $Orders->po_number, ['class' => 'form-control', 'placeholder' => '']) !!}
                    </div>
                    <div class="col-xs-4 form-group @if($errors->has('perfomra_no')) has-error @endif">
                        {!! Form::label('po_date', 'Po Date *', ['class' => 'control-label']) !!}
                        {!! Form::text('po_date', old('po_date'), ['id'=>'po_date','class' => 'form-control datepicker', 'placeholder' => '']) !!}
                    </div>
                    <div class="col-xs-4 form-group @if($errors->has('sup_id')) has-error @endif">
                        {!! Form::label('sup_id', 'Brands *', ['class' => 'control-label']) !!}
                        <select id="sup_id" name="sup_id" class="form-control select2">
                            @if ($SuppliersModel->count())
                                <option value="">Select Brands</option>
                                @foreach($SuppliersModel as $Supplier)
                                    <option value="{{ $Supplier->id }}"{{$Orders->sup_id == $Supplier->id ? 'selected="selected"' : ''}}>{{ $Supplier->sup_name }}</option>
                                @endforeach
                            @endif
                        </select>
                        @if($errors->has('sup_id'))
                            <span class="help-block">
                {{ $errors->first('sup_id') }}
                </span>
                        @endif
                    </div>
                </div>

                    <div id="productmodel_col"></div>
                    <div class="edit-area col-xs-12">

                        <div class="controls">
                            <div class="box-header with-border">
                                <h3 class="box-title">Update Product Detail</h3>
                            </div>

                            <ul class="heading_ul list-style-none text-center" style="float: left; width: 100%; margin-bottom:8px; padding: 0px;">

                                <li class="col-xs-3">
                                    {!! Form::label('product_id', 'Products', ['class' => 'control-label']) !!}
                                </li>
                                <li class="col-xs-2">
                                    {!! Form::label('unit_name', 'Unit Name', ['class' => 'control-label']) !!}
                                </li>
                                <li class="col-xs-2">
                                    {!! Form::label('qty', 'Qunity', ['class' => 'control-label']) !!}
                                </li>
                                <li class="col-xs-2">
                                    {!! Form::label('amount', 'Per Unit Amount', ['class' => 'control-label']) !!}
                                </li>
                                <li class="col-xs-2">
                                    {!! Form::label('amount', 'Total Amount', ['class' => 'control-label']) !!}
                                </li>
                            </ul>

                        </div>
                    </div>
                    {{--{{dd($OrderDetail)}}--}}
                    <div class="col-xs-12">
                        <div>
                            <?php
                                $a = 0;
                            ?>
                            @foreach ($OrderDetail as $Details)
                                    <?php
                                    $a++;
                                    ?>
                            <ul class="example-template" style="float: left; width: 100%; margin-bottom:8px; padding: 0px;">
                                <li class="col-xs-3">
                                    <select id="product_id_" name="product_id[]" class="form-control select2">
                                        @if ($Products->count())
                                            <option value="">Select Product</option>
                                            @foreach($Products as $Product)
                                                <option value="{{ $Product->id }}"{{$Details->product_id == $Product->id ? 'selected="selected"' : ''}}>{{ $Product->products_name  }}</option>
                                            @endforeach
                                        @endif
                                    </select>
                                    @if($errors->has('stock_item_id'))
                                        <span class="help-block">
                                            {{ $errors->first('stock_item_id') }}
                                            </span>
                                    @endif
                                </li>

                                <li class="col-xs-2">
                                    <select id="unit_name" name="unit_name[]" class="form-control select2">
                                        @if ($UnitsModel->count())
                                            <option value="">Select Unit of Measurement</option>
                                            @foreach($UnitsModel as $Units)
                                                <option value="{{ $Units->id }}"{{$Details->unit_name == $Units->id ? 'selected="selected"' : ''}}>{{ $Units->shortcode  }}</option>
                                            @endforeach
                                        @endif
                                    </select>
                                    {{--{!! Form::text('unit_name[]', $Details->unit_name, ['id' => 'unit_name','class' => 'form-control', 'placeholder' => '']) !!}--}}
                                </li>
                                <li class="col-xs-2">
                                    {!! Form::text('qunity[]', $Details->qty, ['id' => 'qunity_'.$a, 'class' => 'form-control', 'placeholder' => '','data-row-id'=>$a]) !!}
                                </li>
                                <li class="col-xs-2">
                                    {!! Form::text('p_amount[]', $Details->unit_price, ['id' => 'p_amount_'.$a, 'class' => 'form-control test', 'placeholder' => '','data-row-id'=>$a]) !!}
                                </li>
                                <li class="col-xs-2">
                                    {!! Form::text('amount[]', $Details->amount, ['id' => 'amount_'.$a, 'class' => 'form-control', 'placeholder' => '','data-row-id'=>$a]) !!}
                                </li>
                                <li class="col-xs-2">
                                    {!! Form::hidden('perchas_id[]', $Details->id, ['id' => 'perchas_id', 'class' => 'form-control', 'placeholder' => '']) !!}
                                </li>
                            </ul>
                            @endforeach
                        </div>

                    </div>
            </div>


        </div>
        <!-- /.box-body -->

        <div class="box-footer">
            {!! Form::submit(trans('global.app_save'), ['class' => 'btn btn-danger globalSaveBtn']) !!}
        </div>
        {!! Form::close() !!}
        {{--@include('admin.entries.voucher.sale_voucher.entries_template')--}}
    </div>
@stop

@section('javascript')

    <script src="{{ url('public/js/admin/orders/update_modify.js') }}" type="text/javascript"></script>

    <script>
          $(document).on('blur','.test',function () {
            amount = $(this).val();
            rowId = $(this).attr('data-row-id');
            quantity = $('#qunity_'+rowId).val();
            total = amount * quantity;
            $('#amount_'+rowId).val(total.toFixed(2));
        })
    </script>
@endsection

resources/views/admin/salesinvoice/fields.blade.php
<div id="11" class="panel-collapse collapse in col-md-12">

    {{ csrf_field() }}
    <div class="form-group col-md-3 @if($errors->has('order_no')) has-error @endif" id="order_no_div">
        {!! Form::label('order_no', 'Order No ', ['class' => 'control-label']) !!}
        {!! Form::select('order_no', $Sales , old('order_no'),
        ['class' => 'form-control select2'  ,'id' => 'order_no', 'onchange' => 'FormControls.fetchFilterrecord();']) !!}
    </div>

    <div class="form-group col-md-3 @if($errors->has('po_no')) has-error @endif">
        {!! Form::label('po_no', 'Po No.', ['class' => 'control-label']) !!}
        {!! Form::text('po_no', old('po_no'), ['class' => 'form-control','id'=> 'po_no','maxlength'=>'15']) !!}
        @if($errors->has('po_no'))
            <span class="help-block">
                {{ $errors->first('po_no') }}
            </span>
        @endif
    </div>

    <div class="form-group col-md-3 @if($errors->has('invoice_date')) has-error @endif">
        {!! Form::label('invoice_date', 'Invoice Date', ['class' => 'control-label']) !!}
        {!! Form::text('invoice_date', date('Y-m-d'), ['class' => 'form-control','readonly' => 'true','id'=> 'invoice_date']) !!}
    </div>

    <div class="form-group col-md-3 @if($errors->has('due_date')) has-error @endif">
        {!! Form::label('due_date', 'Due Date', ['class' => 'control-label']) !!}
        {!! Form::text('due_date', old('due_date'), ['class' => 'form-control datepicker','readonly' => 'true','id'=> 'due_date']) !!}
        @if($errors->has('due_date'))
            <span class="help-block">
                {{ $errors->first('due_date') }}
            </span>
        @endif
    </div>

    <div class="form-group col-md-3 @if($errors->has('rr_no')) has-error @endif">
        {!! Form::label('rr_no', 'R.R No', ['class' => 'control-label']) !!}
        {!! Form::text('rr_no', old('rr_no'), ['class' => 'form-control','readonly' => 'true','id'=> 'rr_no','maxlength'=>'15']) !!}
        @if($errors->has('rr_no'))
            <span class="help-block">
                {{ $errors->first('rr_no') }}
            </span>
        @endif
    </div>


    <div class="form-group col-md-3 @if($errors->has('delivery_type')) has-error @endif" id="delivery_type_div">
        {!! Form::label('delivery_type', 'Delivery Type', ['class' => 'control-label']) !!}
        {!! Form::select('delivery_type', array('' => 'Select Delivery Type') + Config::get('hrm.delivery_type_array') , old('delivery_type'),
         ['class' => 'form-control select2'  ,'id' => 'delivery_type', 'disabled' => 'true']) !!}
        @if($errors->has('delivery_type'))
            <span class="help-block">
                {{ $errors->first('delivery_type') }}
            </span>
        @endif         
    </div>


    <div class="form-group col-md-3 @if($errors->has('installation_date')) has-error @endif">
        {!! Form::label('installation_date', 'Installation Date', ['class' => 'control-label']) !!}
        {!! Form::text('installation_date', old('installation_date'), ['class' => 'form-control datepicker','id'=> 'installation_date',
         'onchange' => 'FormControls.setWarrenty();' ] ) !!}
        @if($errors->has('installation_date'))
            <span class="help-block">
                {{ $errors->first('installation_date') }}
            </span>
        @endif
    </div>



    <div class="form-group col-md-3 @if($errors->has('warrenty')) has-error @endif">
        {!! Form::label('warrenty', 'Warrenty Months', ['class' => 'control-label']) !!}
        {!! Form::text('warrenty', old('warrenty'), ['class' => 'form-control','id'=> 'warrenty' , 'onchange' => 'FormControls.setWarrenty();']) !!}
        @if($errors->has('warrenty'))
            <span class="help-block">
                {{ $errors->first('warrenty') }}
            </span>
        @endif
    </div>

    <div class="form-group col-md-3 @if($errors->has('expires_at')) has-error @endif">
        {!! Form::label('expires_at', 'Expires At', ['class' => 'control-label']) !!}
        {!! Form::text('expires_at', old('expires_at'), ['class' => 'form-control datepicker','readonly' => 'true','id'=> 'expires_at']) !!}
        @if($errors->has('expires_at'))
            <span class="help-block">
                {{ $errors->first('expires_at') }}
            </span>
        @endif
    </div>



    <div class="form-group col-md-6 @if($errors->has('invoice_type')) has-error @endif" id="div_invoice_type">
        {!! Form::label('invoice_type', 'Invoice Type', ['class' => 'control-label']) !!}
        {!! Form::radio('invoice_type', 'taxable', true , ['onclick' => 'FormControls.invoice_type(this)', 'id' => 'taxable_invoice'] ) !!} Taxable
        {!! Form::radio('invoice_type', 'non_taxable',null, ['onclick' => 'FormControls.invoice_type(this)',  'id' => 'non_taxable_invoice'] ) !!} Non Taxable
        @if($errors->has('invoice_type'))
            <span class="help-block">
                {{ $errors->first('invoice_type') }}
            </span>
        @endif
    </div>




    {!! Form::hidden('services_amount', old('services_amount'), [ 'id' => 'services_amount']) !!}
    {!! Form::hidden('products_amount', old('products_amount'), [ 'id' => 'products_amount']) !!}
    {!! Form::hidden('services_tax', old('services_tax'), [ 'id' => 'services_tax']) !!}
    {!! Form::hidden('products_tax', old('products_tax'), [ 'id' => 'products_tax']) !!}

    {!! Form::hidden('amount', old('amount'), [ 'id' => 'amount']) !!}
    {!! Form::hidden('tax_amount', old('tax_amount'), [ 'id' => 'tax_amount']) !!}
    {!! Form::hidden('total_amount', old('total_amount'), [ 'id' => 'total_amount']) !!}
    {!! Form::hidden('payable_amount', old('payable_amount'), [ 'id' => 'payable_amount']) !!}

    <input type="text" style="display: none" id="order_id" name="order_id">
    <input type="text" style="display: none" id="customer_id" name="customer_id">

</div>